test

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,93 +1,93 @@
-name: "Terraform"
-on:
-  push:
-    branches:
-      - main
-      - destroy
-      - apply
-      - argo
+# name: "Terraform"
+# on:
+#   push:
+#     branches:
+#       - main
+#       - destroy
+#       - apply
+#       - argo
   
 
-  pull_request:
-    branches:
-      - main
-      - destroy
-      - apply
-      - argo
+#   pull_request:
+#     branches:
+#       - main
+#       - destroy
+#       - apply
+#       - argo
 
-env:
- AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
- AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
- BUCKET_TF_STATE: ${{secrets.BUCKET_TF_STATE}}
- AWS_REGION: us-east-1
+# env:
+#  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#  BUCKET_TF_STATE: ${{secrets.BUCKET_TF_STATE}}
+#  AWS_REGION: us-east-1
 
-jobs: 
-  terraform:
-    name: "Apply terraform code changes"
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
-        working-directory: ./terr
+# jobs: 
+#   terraform:
+#     name: "Apply terraform code changes"
+#     runs-on: ubuntu-latest
+#     defaults:
+#       run:
+#         shell: bash
+#         working-directory: ./terr
     
-    steps:
-    - name: Checkout source core
-      uses: actions/checkout@v4
+#     steps:
+#     - name: Checkout source core
+#       uses: actions/checkout@v4
 
-    - name: Setup Terraform with specified version on the runner
-      uses: hashicorp/setup-terraform@v3
+#     - name: Setup Terraform with specified version on the runner
+#       uses: hashicorp/setup-terraform@v3
 
 
       
-    - name: Terraform init
-      id: init
-      run: terraform init 
+#     - name: Terraform init
+#       id: init
+#       run: terraform init 
 
-    - name: Terraform format
-      id: fmt
-      run: terraform fmt
+#     - name: Terraform format
+#       id: fmt
+#       run: terraform fmt
     
-    - name: Terraform Validate
-      id: validate
-      run: terraform validate -no-color
+#     - name: Terraform Validate
+#       id: validate
+#       run: terraform validate -no-color
 
-    - name: Terraform Plan
-      id: plan
-      run: terraform plan -no-color -input=false -out planfile
-      continue-on-error: true
-##
-    - name: Terraform plan status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+#     - name: Terraform Plan
+#       id: plan
+#       run: terraform plan -no-color -input=false -out planfile
+#       continue-on-error: true
+# ##
+#     - name: Terraform plan status
+#       if: steps.plan.outcome == 'failure'
+#       run: exit 1
 
-    - name: Terrafrom Apply
-      id: apply
-      if: github.ref == 'refs/heads/apply' && github.event_name == 'push'
-      run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+#     - name: Terrafrom Apply
+#       id: apply
+#       if: github.ref == 'refs/heads/apply' && github.event_name == 'push'
+#       run: terraform apply -auto-approve -input=false -parallelism=1 planfile
     
-    - name: Commit and push
-      id: argo
-      if: steps.apply.outcome == 'success' && github.ref == 'refs/heads/apply' && github.event_name == 'push'
-      run: |
-        git fetch origin
-        git checkout argo
-        git checkout apply -- git/output/output.yaml
-        git add git/output/output.yaml
-        git commit -m "Updated output for argocd" || echo "There is no any changes"
-        git push origin argo
+#     - name: Commit and push
+#       id: argo
+#       if: steps.apply.outcome == 'success' && github.ref == 'refs/heads/apply' && github.event_name == 'push'
+#       run: |
+#         git fetch origin
+#         git checkout argo
+#         git checkout apply -- git/output/output.yaml
+#         git add git/output/output.yaml
+#         git commit -m "Updated output for argocd" || echo "There is no any changes"
+#         git push origin argo
        
     
-    - name: Terrafrom Destroy
-      id: destroy
-      if: github.ref == 'refs/heads/destroy' && github.event_name == 'push'
-      run: |
-        terraform destroy -auto-approve -input=false -parallelism=1 
-        git fetch origin
-        git checkout argo
-        :> git/output/output.yaml 
-        git add git/output/output.yaml
-        git commit -m "Clear output.yaml" || echo "There is no any changes"
-        git push origin argo
+#     - name: Terrafrom Destroy
+#       id: destroy
+#       if: github.ref == 'refs/heads/destroy' && github.event_name == 'push'
+#       run: |
+#         terraform destroy -auto-approve -input=false -parallelism=1 
+#         git fetch origin
+#         git checkout argo
+#         :> git/output/output.yaml 
+#         git add git/output/output.yaml
+#         git commit -m "Clear output.yaml" || echo "There is no any changes"
+#         git push origin argo
     
 
   
